#!/usr/bin/env bash
# Cotne Nazarashvili aka THECOTNE <cotne.95@gmail.com>
source tasker-core

function install { # Install project
    composer install
    php artisan migrate:refresh --seed
    clear
    npm install
    build
}

function update { # Update project
    composer update
    php artisan migrate:refresh --seed
    clear
    npm install
    build
}

function watch { # Run webpack and gulp in watch mode
    webpack -w & gulp watch
}

function build { # Run webpack and gulp
    gulp && webpack
}

function webpack { # webpack module bundler
    eval "command webpack ${@}"
}

function gulp { # gulp.js - the streaming build system
    eval "command gulp ${@}"
}

function clear { # Resets all of compiled class files, cached views, cached configs etc.
    php artisan clear
}

_bootstrap "${@}"
