#!/usr/bin/env bash
set -e

if [ ! -f ./node_modules/@thecotne/tasker/tasker-core ]; then
    npm install
fi

source ./node_modules/@thecotne/tasker/tasker-core

function taskNameOne { # task description one
    echo "doing task one"
}

function taskNameTwo { # task description two
    echo "doing task two"
}

_bootstrap "${@}"
