#!/usr/bin/env bash
set -e

if [ ! -f ./node_modules/@thecotne/tasker/tasker-core ]; then
    yarn
fi

source ./node_modules/@thecotne/tasker/tasker-core

function task-name-one { # task description one
    echo "doing task one"
}

function task-name-two { # task description two
    echo "doing task two"
}

_bootstrap "${@}"
