#!/usr/bin/env node
const readline = require('readline')

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: false
})

let maxLength = 0

rl.on('line', line => {
  if (line.length > maxLength) {
    maxLength = line.length
  }
})

rl.on('close', () => {
  console.log(maxLength)
})
